FROM diego/nodejs
RUN  apt-get install -yq --no-install-recommends curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -yq nodejs \
    apt-get install -yq npm
RUN mkdir -p /root/admin/pspotify
WORKDIR /root/admin/pspotify

COPY ./dockerfiles/pspotify/admin/start.sh .
RUN chmod +x /root/admin/pspotify/start.sh

ENTRYPOINT [ "./start.sh" ]