FROM diego/nodejs
RUN apt-get update && apt-get install -y \
    nodejs
RUN mkdir -p /root/admin/pspotify
WORKDIR /root/admin/pspotify

COPY ./dockerfiles/pspotify/admin/start.sh .
RUN chmod +x /root/admin/pspotify/start.sh

ENTRYPOINT [ "./start.sh" ]