FROM dmorrid/nodejs

# Definir el directorio de trabajo donde está el proyecto
WORKDIR /root/admin/node/proyecto/pproyecto

# Instalar dependencias y construir el proyecto
RUN npm install
RUN npm run build

# Copiar los archivos construidos al directorio de nginx
RUN cp -r dist/* /var/www/html/

# Volver al directorio de administración de pspotify
RUN mkdir -p /root/admin/pspotify
WORKDIR /root/admin/pspotify

COPY ./dockerfiles/pspotify/admin/start.sh .
RUN chmod +x /root/admin/pspotify/start.sh

ENTRYPOINT [ "./start.sh" ]