FROM diego/nginx

RUN apt-get update && \
    apt-get install -yq --no-install-recommends curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -yq nodejs \
    apt get install npm

RUN mkdir -p /root/admin/node
RUN mkdir -p /root/admin/node/proyecto/pproyecto
WORKDIR /root/admin/node
COPY ./proyecto/pproyecto /root/admin/node/proyecto/pproyecto

COPY ./dockerfiles/node/admin/start.sh .
RUN chmod +x /root/admin/node/start.sh

ENTRYPOINT [ "./start.sh" ]