FROM diego/nginx

RUN apt update && apt install -yq curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt install -yq nodejs

RUN mkdir -p /root/admin/node
RUN mkdir -p /root/admin/node/proyecto/pproyecto
WORKDIR /root/admin/node
COPY ./proyecto/pproyecto/* /root/admin/node/proyecto/pproyecto

COPY ./dockerfiles/node/admin/start.sh .
RUN chmod +x /root/admin/node/start.sh

ENTRYPOINT [ "./start.sh" ]