FROM diego/ubbase

USER root
RUN apt update && apt install -yq --no-install-recommends \
    nmap




RUN mkdir -p /root/admin/logs
WORKDIR /root/admin/logs
COPY ./dockerfiles/ubsecurity .
RUN chmod +x /root/admin/logs/start.sh

ENTRYPOINT ["./start.sh"]