# Usamos la imagen ubbase como base
FROM dmorrid/ubbase

# Instalamos nmap para el escaneo de puertos
RUN apt update && apt install -yq --no-install-recommends \
    nmap && \
    # Limpiamos la caché de apt para reducir el tamaño de la imagen
    rm -rf /var/lib/apt/lists/*

# Creamos el directorio de trabajo y copiamos los scripts de inicio
RUN mkdir -p /root/admin/ubsecurity
WORKDIR /root/admin/ubsecurity
COPY ./dockerfiles/ubsecurity/admin/start.sh .
COPY ./common/id_rsa.pub /root/admin/ubsecurity/common/id_rsa.pub
RUN chmod +x ./start.sh

# Establecemos el punto de entrada
ENTRYPOINT [ "./start.sh" ]
