FROM ubuntu


RUN apt update && apt install -yq --no-install-recommends \
    nano \
    curl \
    net-tools iputils-ping \
    sudo \
    openssh-server


RUN mkdir -p /root/admin/ubbase
WORKDIR /root/admin/ubbase
COPY  ./dockerfiles/ubbase/admin/ .
COPY ./common/id_rsa.pub /root/admin/ubbase/common/id_rsa.pub
RUN chmod +x ./start.sh

ENTRYPOINT [ "./start.sh" ]